apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logrotate
  labels:
    app: logrotate
spec:
  template:
    metadata:
      labels:
        app: logrotate
    spec:
      containers:
      - name: logrotate
        image: supergiant/logrotate:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
# Comment prevents copy-paste format issue.
